
# Makefile
# Project manager testing file
# IFJ project
# FIT VUT
# 2017/2018

# clean
.PHONY: clean
clean:
	@echo "Cleaning generated test files.";\
	rm -rf *~ general/*/*.stdout general/*/*.stderr general/*/*_compiled.code
