#!/bin/bash

cd .. && rebuild > /dev/null && cd test

log="log"

test_count=0
test_succ=0
for n in $(find *.data -type f ); do
  printf "TEST $n: "
  printf "TEST $n: " >> result
  if [ "$1" = "-v" ]; then
    valgrind ../ifj < "$n"
  else
    valgrind ../ifj < "$n" 2> /dev/null >> log
  fi

  if [ "$?" = "0" ]; then
    echo "[OK]" >> result
    printf "[OK]"
    test_succ=$((test_succ+1))
  else
    echo "[FAIL]" >> result
    printf "[FAIL]"
  fi
  test_count=$((test_count+1))

  printf " "
  for n in $(seq 1 3); do
    printf "."
    sleep 0.5
  done
  sleep 2
  echo ""
done
echo "---------------"
echo "TOTAL: $test_succ/$test_count" >> result
echo "TOTAL: $test_succ/$test_count"
