#!/bin/bash

# raises error
raise() {
  echo "ERROR: $@" >&2
  exit 1
}


init() {
  if [ -d "test" ]; then
    printf "Testing is being initialized"
    for n in $(seq 1 3); do
      printf "."
      sleep 0.5
    done
    printf "\n\n"
  else
    raise "ERROR: Dir does not exist!"
  fi
}


test_count=0
test_succ=0
launch_test() {
  ./ifj < "$1" > "$1.out" 2> "$1.err"
  ./ifj < "$1" > "$1.stdout" 2> "$1.stderr"
  #echo "a" >> "$1.stdout"
  if [ "$(cat "$1.out")" = "$(cat "$1.stdout")" ]; then
    test_succ=$((test_succ+1))
    echo "[OK]"
  else
    echo "[ERROR]"
  fi
}


run_all_tests()
{
  echo "======= Cleaning with Makefile ======="
  make clean
  echo "======= Building with Makefile ======="
  make
  echo "======================================"
  sleep 2

  for t in $(find ./test/ -type f -name *.test); do
    test_count=$((test_count+1))

    printf "TEST $test_count: "
    printf "$t " | sed "s/^\.\/test\///"

    launch_test "$t"

    sleep 1
  done

  sleep 0.5
  echo "======================================"
  echo "DONE."
  sleep 0.5
  echo "$test_succ / $test_count successful."
}


# begin
init

# running tests
run_all_tests
